import Phy from './assets/magnet.svg';
export const subject_item =[
    {
        id:1,
        abv:"eng",
        title:"English"
    },
    {
        id:2,
        abv:"math",
        title:"Mathematics"
    },
    {
        id:3,
        abv:"phy",
        title:"Physics",
        img:Phy
    },
    {
        id:4,
        abv:"chem",
        title:"Chemistry"
    },
    {
        id:5,
        abv:"bio",
        title:"Biology"
    },
    {
        id:6,
        abv:"agric",
        title:"Agricultural Science"
    },
    {
        id:7,
        abv:"econs",
        title:"Economics"
    },
    {
        id:8,
        abv:"geo",
        title:"Geography"
    },
    {
        id:9,
        abv:"comm",
        title:"Commerce"
    },
    {
        id:10,
        abv:"gov",
        title:"Government"
    },
    {
        id:11,
        abv:"lit",
        title:"Literature"
    },
    {
        id:12,
        abv:"eng",
        title:"English"
    },
    {
        id:13,
        abv:"crk",
        title:"Christian Religious Studies"
    },
    {
        id:14,
        abv:"irk",
        title:"Islamic Religious Studies"
    },
    {
        id:15,
        abv:"fr",
        title:"French"
    },
]